[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
proc-macro2 = "1.0.81"
quote = "1.0.36"
syn = { version = "2.0.60", features = ["full"] }
tauri = "^2.0.0-beta"

[lib]
proc-macro = true
